github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: true

tasks:
  - name: Nextcloud Server
    init: |
      cd gitpod
      docker-compose up --no-start
    command: |
      git config core.fileMode false
      # Both gitpod and Nextcloud need read/write acess
      # Obviously not recommended for a production system
      sudo chown -R www-data:www-data ${GITPOD_REPO_ROOT}
      sudo chmod -R 777 ${GITPOD_REPO_ROOT}
      cd gitpod
      docker-compose up

  - name: Dependency install
    init: make dev-setup
    command: exit

  - name: Frontend
    command: make watch-js

  - name: Terminal
    command: clear

ports:
  - port: 8080
    onOpen: open-browser
    visibility: private
  - port: 8081
    visibility: private
    onOpen: ignore
