tasks:
  - name: Dev Server
    init: |
      cd gitpod
      docker-compose up --no-start
    command: |
      git config core.fileMode false
      chmod -R 777 .
      cd gitpod
      docker-compose up

ports:
  - port: 8080
