# This is for gitpod, DO NOT USE THIS TO HOST YOUR NEXTCLOUD

version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=5)7t}5H$c@_Rs(?3aA{s40y6&
      - MYSQL_PASSWORD=5)7t}5H$c@_Rs(?3aA{s40y6&
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
      - /workspace/biblio/:/var/www/html/apps/biblio/
    environment:
      - MYSQL_PASSWORD=5)7t}5H$c@_Rs(?3aA{s40y6&
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=dev
      - NEXTCLOUD_ADMIN_PASSWORD=t2qQ1C6ktYUv7
      - NEXTCLOUD_TRUSTED_DOMAINS=*.gitpod.io