name: Lint

on:
  pull_request:
  push:
    branches:
      - main
      - stable*

permissions:
  contents: read

concurrency:
  group: lint-info-xml-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  xml-linters:
    runs-on: ubuntu-latest

    name: info.xml lint
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v3

      - name: Download schema
        run: wget https://raw.githubusercontent.com/nextcloud/appstore/master/nextcloudappstore/api/v1/release/info.xsd

      - name: Lint info.xml
        uses: ChristophWurst/xmllint-action@d18a551aab4728e4af449617638600634d7a48cb # v1
        with:
          xml-file: ./appinfo/info.xml
          xml-schema-file: ./info.xsd